site_name:           MCHhammer
repo_url:            https://github.com/etorkia/MCHammer.jl
site_description:    Monte-Carlo Simulation for Julia
site_author:         Eric Torkia
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math # For LaTeX

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'userguide'

pages:
- Overview: index.md
- Manual:
  - Core Functions: manual/functions.md
  - Charting: manual/charts.md
  - Time Series: manual/time_series.md
- Tutorial:
  - Quick Start Guide: /tutorials/1_first_model.md
  - Basic Model with Correlation: tutorials/2_Correlated_Model.md
  - Simulated Time Series: tutorials/NPV_tesmodel.md
  - Data Analysis: tutorials/DataAnalysis.md
